version: "3.9"
services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --env-file .env
